# Generated by Django 6.0 on 2025-12-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='tel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
