# Generated by Django 6.0 on 2025-12-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_offer_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='tel',
        ),
    ]
